// Model catalogue for the comparator. `xrt` (×real-time speed) and `wer` (avg error %) are
// PLACEHOLDERS from published specs until benchmark/results.json lands — see scripts/merge-bench.
export type Device = "on-device" | "cloud";

export interface Model {
  id: string;
  label: string;
  engine: "Whisper" | "Parakeet" | "SenseVoice" | "Apple" | "Groq" | "Moonshine";
  device: Device;
  size: string;          // on-disk size, or "—" for cloud
  langs: string[] | "all"; // ISO codes it handles ("all" ≈ 99 Whisper languages)
  translate: boolean;    // can translate to English
  xrt: number | null;    // × real-time (higher = faster); null = pending
  wer: number | null;    // average word/char error %, lower = better
  measured: boolean;     // true once it's our own benchmark, false = published estimate
  note?: string;
  available?: boolean;   // false = benchmarked but not shipped in the app (shown with an asterisk)
}

export const LANGUAGES: Record<string, string> = {
  en: "English", fr: "Français", de: "Deutsch", es: "Español", it: "Italiano",
  pt: "Português", ru: "Русский", vi: "Tiếng Việt", zh: "中文", ja: "日本語",
  ko: "한국어", ar: "العربية", hi: "हिन्दी",
};

const EU = ["en", "fr", "de", "es", "it", "pt", "ru"];

export const MODELS: Model[] = [
  { id: "whisper-tiny",   label: "Whisper tiny",          engine: "Whisper",    device: "on-device", size: "75 MB",  langs: "all", translate: true,  xrt: 32,  wer: 28,   measured: false },
  { id: "whisper-base",   label: "Whisper base",          engine: "Whisper",    device: "on-device", size: "142 MB", langs: "all", translate: true,  xrt: 20,  wer: 22,   measured: false },
  { id: "whisper-small",  label: "Whisper small",         engine: "Whisper",    device: "on-device", size: "466 MB", langs: "all", translate: true,  xrt: 11,  wer: 15,   measured: false },
  { id: "whisper-medium", label: "Whisper medium",        engine: "Whisper",    device: "on-device", size: "1.5 GB", langs: "all", translate: true,  xrt: 5,   wer: 11.5, measured: false },
  { id: "whisper-large",  label: "Whisper large-v3",      engine: "Whisper",    device: "on-device", size: "3.1 GB", langs: "all", translate: true,  xrt: 2.5, wer: 9.8,  measured: false },
  { id: "whisper-turbo",  label: "Whisper large-v3-turbo",engine: "Whisper",    device: "on-device", size: "1.6 GB", langs: "all", translate: true,  xrt: 6,   wer: 11,   measured: false },
  { id: "distil-large-v3", label: "Distil large-v3",     engine: "Whisper",    device: "on-device", size: "1.5 GB", langs: ["en"], translate: false, xrt: null, wer: null, measured: false, note: "Distilled large-v3 — English only, much faster" },
  { id: "apple-speech",   label: "Apple Speech",          engine: "Apple",      device: "on-device", size: "System", langs: ["en","fr","de","es","it","pt","zh","ja","ko"], translate: false, xrt: null, wer: null, measured: false, note: "Built into macOS 26+ — models managed by the system" },
  { id: "parakeet-v3",    label: "Parakeet v3",           engine: "Parakeet",   device: "on-device", size: "2.4 GB", langs: EU,    translate: false, xrt: 40,  wer: 9,    measured: false, note: "Live preview while you speak" },
  { id: "sensevoice",     label: "SenseVoice",            engine: "SenseVoice", device: "on-device", size: "239 MB", langs: ["zh","ja","ko","en"], translate: false, xrt: 28, wer: 10, measured: false },
  { id: "moonshine-base", label: "Moonshine base",        engine: "Moonshine",  device: "on-device", size: "141 MB", langs: ["en","es","ar","ja","vi","zh"], translate: false, xrt: null, wer: null, measured: false, available: false, note: "Not shipped — set aside after our benchmark, given accuracy and language coverage." },
  { id: "groq-turbo",     label: "Groq large-v3-turbo",   engine: "Groq",       device: "cloud",     size: "—",      langs: "all", translate: false, xrt: 216, wer: 12,   measured: false, note: "Cloud — audio leaves your Mac" },
  { id: "groq-large",     label: "Groq large-v3",         engine: "Groq",       device: "cloud",     size: "—",      langs: "all", translate: true,  xrt: 189, wer: 10.3, measured: false, note: "Cloud — audio leaves your Mac" },
];

export function supportsLang(m: Model, code: string): boolean {
  return m.langs === "all" || m.langs.includes(code);
}

/// On-disk size in MB, or null for cloud models ("—").
export function sizeMB(m: Model): number | null {
  const match = m.size.match(/([\d.]+)\s*(MB|GB)/i);
  if (!match) return null;
  const n = parseFloat(match[1]);
  return match[2].toUpperCase() === "GB" ? n * 1024 : n;
}

// Measured benchmark data (FLEURS, Apple Silicon) generated by benchmark/merge-bench.py.
// Falls back to the published estimates above when a model (or language) hasn't been measured.
import bench from "./benchmark.json";

export interface Metric { xrt: number | null; err: number | null; measured: boolean }

export function metrics(m: Model, lang: string): Metric {
  const b = (bench as Record<string, any>)[m.id];
  if (b) {
    if (lang !== "any" && b.byLang?.[lang]) {
      return { xrt: b.byLang[lang].xrt, err: b.byLang[lang].err, measured: true };
    }
    if (b.overall && b.overall.xrt != null) {
      return { xrt: b.overall.xrt, err: b.overall.err, measured: true };
    }
  }
  return { xrt: m.xrt, err: m.wer, measured: false };
}
